// Post-build: give every prerendered page a `Link` header so Cloudflare Early
// Hints (on for the zone) can send `103` with the page's critical resources
// while the HTML is still in flight.
//
// The pages are served straight from Workers Static Assets, so the only place
// a response header can come from is dist/client/_headers. The resource names
// are content-hashed per build, which is why this reads the built HTML instead
// of listing them by hand — a hand-written list would go stale on the next
// build and preload files that no longer exist.
//
// Exit 1 when nothing was found: an empty result is a broken build, not a pass.

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

const root = new URL("../dist/client/", import.meta.url).pathname;
const headersPath = join(root, "_headers");
const BEGIN = "# >>> early-hints (build-generated by scripts/early-hints.mjs)";
const END = "# <<< early-hints";

function* htmlFiles(dir) {
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		const path = join(dir, entry.name);
		if (entry.isDirectory()) yield* htmlFiles(path);
		else if (entry.name.endsWith(".html")) yield path;
	}
}

/** `contact.html` → `/contact`, `index.html` → `/` (build.format: "file"). */
function routeOf(file) {
	const rel = relative(root, file).split(sep).join("/");
	const route = `/${rel}`.replace(/(?:\/index)?\.html$/, "");
	return route === "" ? "/" : route;
}

const attr = (tag, name) => tag.match(new RegExp(`\\s${name}="([^"]*)"`))?.[1];

function linksFor(html) {
	const links = [];
	for (const [tag] of html.matchAll(/<link\s[^>]*>/g)) {
		const rel = attr(tag, "rel");
		const href = attr(tag, "href");
		if (!href?.startsWith("/")) continue;
		if (rel === "stylesheet") links.push(`<${href}>; rel=preload; as=style`);
		else if (rel === "preload" && attr(tag, "as") === "font")
			links.push(`<${href}>; rel=preload; as=font; type="font/woff2"; crossorigin`);
	}
	for (const [tag] of html.matchAll(/<script\s[^>]*>/g)) {
		const src = attr(tag, "src");
		if (src?.startsWith("/") && attr(tag, "type") === "module")
			links.push(`<${src}>; rel=modulepreload`);
	}
	return [...new Set(links)];
}

const rules = [];
for (const file of htmlFiles(root)) {
	const route = routeOf(file);
	if (route === "/404") continue; // served for unknown paths; no stable route to hint
	const links = linksFor(readFileSync(file, "utf8"));
	if (links.length > 0) rules.push(`${route}\n  Link: ${links.join(", ")}`);
}

if (rules.length === 0) {
	console.error("early-hints: no prerendered HTML with local resources under dist/client");
	process.exit(1);
}

const existing = readFileSync(headersPath, "utf8");
const start = existing.indexOf(BEGIN);
const kept =
	start === -1
		? existing
		: existing.slice(0, start) + existing.slice(existing.indexOf(END, start) + END.length);
const block = [BEGIN, ...rules, END].join("\n");
writeFileSync(headersPath, `${kept.trimEnd()}\n\n${block}\n`);
console.log(`early-hints: ${rules.length} routes → ${relative(process.cwd(), headersPath)}`);
